version: '3.7'

volumes:
  ballin_postgres:
    external: true

services:
  db:
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ballin_postgres:/var/lib/postgresql/data/
  django-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
    command:
      - '/code/bin/wait-for-it'
      - 'db:5432'
      - '--'
      - 'python'
      - '/code/app/manage.py'
      - 'runserver'
      - '0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3001:3001"
    depends_on:
      - db
